@echo off
echo Starting Rehman Fish Shop Application in Development Mode...

echo Installing dependencies...
npm install

echo Starting MongoDB (make sure MongoDB is installed and in your PATH)...
start mongod

echo Starting the application server with nodemon for development...
npm run dev

echo.
echo Application should now be running at http://localhost:3000
echo Press any key to close this window...
pause >nul